// <auto-generated />
using System;
using CSMWebsite2023.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSMWebsite2023.EntityFramework.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20231013063712_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CSMWebsite2023.Data.Models.AdComment", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ReplyToId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SchoolAdId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolAdId");

                    b.HasIndex("UserId");

                    b.ToTable("AdComments");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.AdMedium", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MediaType")
                        .HasColumnType("int");

                    b.Property<Guid?>("SchoolAdId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SchoolAdId");

                    b.HasIndex("UserId");

                    b.ToTable("AdMedia");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.AdReaction", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ReactionType")
                        .HasColumnType("int");

                    b.Property<Guid?>("SchoolAdId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolAdId");

                    b.HasIndex("UserId");

                    b.ToTable("AdReactions");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.AdShare", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("SchoolAdId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolAdId");

                    b.HasIndex("UserId");

                    b.ToTable("AdShares");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.Chat", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("857918e8-67dd-4c35-b70d-936ba0fc0c01"),
                            CreatedAt = new DateTime(2023, 10, 13, 14, 37, 11, 905, DateTimeKind.Local).AddTicks(8810),
                            Name = "School Friends Chat",
                            UpdatedAt = new DateTime(2023, 10, 13, 14, 37, 11, 905, DateTimeKind.Local).AddTicks(8809)
                        },
                        new
                        {
                            Id = new Guid("857918e8-67dd-4c35-b70d-936ba0fc0c02"),
                            CreatedAt = new DateTime(2023, 10, 13, 14, 37, 11, 905, DateTimeKind.Local).AddTicks(8813),
                            Name = "Family Chat",
                            UpdatedAt = new DateTime(2023, 10, 13, 14, 37, 11, 905, DateTimeKind.Local).AddTicks(8813)
                        },
                        new
                        {
                            Id = new Guid("857918e8-67dd-4c35-b70d-936ba0fc0c03"),
                            CreatedAt = new DateTime(2023, 10, 13, 14, 37, 11, 905, DateTimeKind.Local).AddTicks(8816),
                            Name = "CIS 214 Chat",
                            UpdatedAt = new DateTime(2023, 10, 13, 14, 37, 11, 905, DateTimeKind.Local).AddTicks(8815)
                        },
                        new
                        {
                            Id = new Guid("857918e8-67dd-4c35-b70d-936ba0fc0c04"),
                            CreatedAt = new DateTime(2023, 10, 13, 14, 37, 11, 905, DateTimeKind.Local).AddTicks(8854),
                            Name = "History Class Chat",
                            UpdatedAt = new DateTime(2023, 10, 13, 14, 37, 11, 905, DateTimeKind.Local).AddTicks(8854)
                        },
                        new
                        {
                            Id = new Guid("857918e8-67dd-4c35-b70d-936ba0fc0c05"),
                            CreatedAt = new DateTime(2023, 10, 13, 14, 37, 11, 905, DateTimeKind.Local).AddTicks(8857),
                            Name = "Barcada Chat",
                            UpdatedAt = new DateTime(2023, 10, 13, 14, 37, 11, 905, DateTimeKind.Local).AddTicks(8856)
                        });
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.ChatMedium", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ChatId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ChatMessageId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MediaType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("ChatMessageId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMedia");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.ChatMember", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ChatId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMembers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3c237aa-97b9-481b-bc32-5ca036b9b501"),
                            ChatId = new Guid("857918e8-67dd-4c35-b70d-936ba0fc0c03"),
                            CreatedAt = new DateTime(2023, 10, 13, 14, 37, 11, 905, DateTimeKind.Local).AddTicks(8866),
                            UpdatedAt = new DateTime(2023, 10, 13, 14, 37, 11, 905, DateTimeKind.Local).AddTicks(8865),
                            UserId = new Guid("91a4e383-5133-4675-ad4e-24ef11bb4c00")
                        },
                        new
                        {
                            Id = new Guid("a3c237aa-97b9-481b-bc32-5ca036b9b502"),
                            ChatId = new Guid("857918e8-67dd-4c35-b70d-936ba0fc0c03"),
                            CreatedAt = new DateTime(2023, 10, 13, 14, 37, 11, 905, DateTimeKind.Local).AddTicks(8869),
                            UpdatedAt = new DateTime(2023, 10, 13, 14, 37, 11, 905, DateTimeKind.Local).AddTicks(8869),
                            UserId = new Guid("91a4e383-5133-4675-ad4e-24ef11bb4c01")
                        });
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.ChatMessage", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ChatId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ReplyToId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("39c059ac-0cee-4daa-a8bd-2ee9d7050030"),
                            ChatId = new Guid("857918e8-67dd-4c35-b70d-936ba0fc0c03"),
                            CreatedAt = new DateTime(2023, 10, 13, 14, 37, 11, 905, DateTimeKind.Local).AddTicks(8877),
                            Message = "Hi, Nunc at turpis faucibus, viverra ipsum non, vestibulum nibh.",
                            UpdatedAt = new DateTime(2023, 10, 13, 14, 37, 11, 905, DateTimeKind.Local).AddTicks(8877),
                            UserId = new Guid("91a4e383-5133-4675-ad4e-24ef11bb4c00")
                        },
                        new
                        {
                            Id = new Guid("39c059ac-0cee-4daa-a8bd-2ee9d7050031"),
                            ChatId = new Guid("857918e8-67dd-4c35-b70d-936ba0fc0c03"),
                            CreatedAt = new DateTime(2023, 10, 13, 14, 37, 11, 905, DateTimeKind.Local).AddTicks(8881),
                            Message = "Hello, Mauris condimentum urna vel diam gravida vulputate",
                            UpdatedAt = new DateTime(2023, 10, 13, 14, 37, 11, 905, DateTimeKind.Local).AddTicks(8880),
                            UserId = new Guid("91a4e383-5133-4675-ad4e-24ef11bb4c01")
                        });
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.ChatReaction", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ChatId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ChatMessageId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ReactionType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("ChatMessageId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatReactions");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.Group", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6d073e1-1948-44ac-a1c7-c85f26457f32"),
                            Name = "Name"
                        });
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.GroupMember", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.GroupPost", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupPost");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.GroupPostMedium", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("GroupPostId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("MediaType")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("GroupPostId");

                    b.ToTable("GroupPostMedia");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.Research", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Abstract")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Researches");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6d073e1-1948-44ac-a1c7-c85f26457f30"),
                            Abstract = "Abstract",
                            Title = "Title"
                        });
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.ResearchAuthor", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ResearchId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ResearchId");

                    b.HasIndex("UserId");

                    b.ToTable("ResearchAuthors");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.ResearchComment", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ReplyToId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ResearchId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ResearchId");

                    b.HasIndex("UserId");

                    b.ToTable("ResearchComments");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.ResearchMedium", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MediaType")
                        .HasColumnType("int");

                    b.Property<Guid?>("ResearchId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ResearchId");

                    b.HasIndex("UserId");

                    b.ToTable("ResearchMedia");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.ResearchReaction", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ReactionType")
                        .HasColumnType("int");

                    b.Property<Guid?>("ResearchId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ResearchId");

                    b.HasIndex("UserId");

                    b.ToTable("ResearchReactions");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.ResearchShare", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ResearchId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ResearchId");

                    b.HasIndex("UserId");

                    b.ToTable("ResearchShares");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.SchoolAd", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("SchoolAds");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6d073e1-1948-44ac-a1c7-c85f26457f34"),
                            Description = "Description",
                            Title = "Title"
                        });
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.SchoolEvent", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("SchoolEvents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6d073e1-1948-44ac-a1c7-c85f26457f36"),
                            Date = new DateTime(2023, 11, 13, 14, 37, 11, 905, DateTimeKind.Local).AddTicks(8904),
                            Description = "A party for students to get to get to know one another",
                            Title = "Acquaintance Party"
                        });
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.SchoolEventComment", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ReplyToId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SchoolEventId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SchoolEventId");

                    b.HasIndex("UserId");

                    b.ToTable("SchoolEventComments");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.SchoolEventMedium", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MediaType")
                        .HasColumnType("int");

                    b.Property<Guid?>("SchoolEventId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SchoolEventId");

                    b.HasIndex("UserId");

                    b.ToTable("SchoolEventMedia");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.SchoolEventReaction", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("SchoolEventId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolEventId");

                    b.HasIndex("UserId");

                    b.ToTable("SchoolEventReactions");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.SchoolEventShare", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("SchoolEventId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolEventId");

                    b.HasIndex("UserId");

                    b.ToTable("SchoolEventShares");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.SchoolPost", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SchoolPosts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("caf9cd32-5e33-451d-a756-cad109eabef2"),
                            Content = "TEST CONTENT",
                            Title = "Title",
                            UserId = new Guid("91a4e383-5133-4675-ad4e-24ef11bb4c01")
                        });
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.SchoolPostComment", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ReplyToId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SchoolPostId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolPostId");

                    b.HasIndex("UserId");

                    b.ToTable("SchoolPostComments");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.SchoolPostMedium", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MediaType")
                        .HasColumnType("int");

                    b.Property<Guid?>("SchoolPostId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SchoolPostId");

                    b.ToTable("SchoolPostMedia");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6d073e1-1948-44ac-a1c7-c85f26457f28"),
                            MediaType = 1,
                            SchoolPostId = new Guid("caf9cd32-5e33-451d-a756-cad109eabef2"),
                            Value = "/schoolposts/caf9cd32-5e33-451d-a756-cad109eabef2/main.png"
                        });
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.SchoolPostReaction", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ReactionType")
                        .HasColumnType("int");

                    b.Property<Guid?>("SchoolPostId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolPostId");

                    b.HasIndex("UserId");

                    b.ToTable("SchoolPostReactions");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.SchoolPostShare", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("SchoolPostId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolPostId");

                    b.HasIndex("UserId");

                    b.ToTable("SchoolPostShares");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.User", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("91a4e383-5133-4675-ad4e-24ef11bb4c00"),
                            CreatedAt = new DateTime(2023, 10, 13, 14, 37, 11, 905, DateTimeKind.Local).AddTicks(8799),
                            EmailAddress = "etirel@mailinator.com",
                            FirstName = "Elspeth",
                            LastName = "Tirel",
                            UpdatedAt = new DateTime(2023, 10, 13, 14, 37, 11, 905, DateTimeKind.Local).AddTicks(8789)
                        },
                        new
                        {
                            Id = new Guid("91a4e383-5133-4675-ad4e-24ef11bb4c01"),
                            CreatedAt = new DateTime(2023, 10, 13, 14, 37, 11, 905, DateTimeKind.Local).AddTicks(8806),
                            EmailAddress = "jbeleren@mailinator.com",
                            FirstName = "Jace",
                            LastName = "Beleren",
                            UpdatedAt = new DateTime(2023, 10, 13, 14, 37, 11, 905, DateTimeKind.Local).AddTicks(8806)
                        });
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.AdComment", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.SchoolAd", "SchoolAd")
                        .WithMany()
                        .HasForeignKey("SchoolAdId");

                    b.HasOne("CSMWebsite2023.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("SchoolAd");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.AdMedium", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.SchoolAd", "SchoolAd")
                        .WithMany()
                        .HasForeignKey("SchoolAdId");

                    b.HasOne("CSMWebsite2023.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("SchoolAd");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.AdReaction", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.SchoolAd", "SchoolAd")
                        .WithMany()
                        .HasForeignKey("SchoolAdId");

                    b.HasOne("CSMWebsite2023.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("SchoolAd");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.AdShare", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.SchoolAd", "SchoolAd")
                        .WithMany()
                        .HasForeignKey("SchoolAdId");

                    b.HasOne("CSMWebsite2023.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("SchoolAd");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.ChatMedium", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId");

                    b.HasOne("CSMWebsite2023.Data.Models.ChatMessage", "ChatMessage")
                        .WithMany()
                        .HasForeignKey("ChatMessageId");

                    b.HasOne("CSMWebsite2023.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Chat");

                    b.Navigation("ChatMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.ChatMember", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId");

                    b.HasOne("CSMWebsite2023.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.ChatMessage", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId");

                    b.HasOne("CSMWebsite2023.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.ChatReaction", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId");

                    b.HasOne("CSMWebsite2023.Data.Models.ChatMessage", "ChatMessage")
                        .WithMany()
                        .HasForeignKey("ChatMessageId");

                    b.HasOne("CSMWebsite2023.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Chat");

                    b.Navigation("ChatMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.GroupMember", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("CSMWebsite2023.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.GroupPost", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.GroupPostMedium", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("CSMWebsite2023.Data.Models.GroupPost", "GroupPost")
                        .WithMany()
                        .HasForeignKey("GroupPostId");

                    b.Navigation("Group");

                    b.Navigation("GroupPost");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.ResearchAuthor", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.Research", "Research")
                        .WithMany()
                        .HasForeignKey("ResearchId");

                    b.HasOne("CSMWebsite2023.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Research");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.ResearchComment", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.Research", "Research")
                        .WithMany()
                        .HasForeignKey("ResearchId");

                    b.HasOne("CSMWebsite2023.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Research");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.ResearchMedium", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.Research", "Research")
                        .WithMany()
                        .HasForeignKey("ResearchId");

                    b.HasOne("CSMWebsite2023.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Research");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.ResearchReaction", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.Research", "Research")
                        .WithMany()
                        .HasForeignKey("ResearchId");

                    b.HasOne("CSMWebsite2023.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Research");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.ResearchShare", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.Research", "Research")
                        .WithMany()
                        .HasForeignKey("ResearchId");

                    b.HasOne("CSMWebsite2023.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Research");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.SchoolEventComment", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.SchoolEvent", "SchoolEvent")
                        .WithMany()
                        .HasForeignKey("SchoolEventId");

                    b.HasOne("CSMWebsite2023.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("SchoolEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.SchoolEventMedium", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.SchoolEvent", "SchoolEvent")
                        .WithMany()
                        .HasForeignKey("SchoolEventId");

                    b.HasOne("CSMWebsite2023.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("SchoolEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.SchoolEventReaction", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.SchoolEvent", "SchoolEvent")
                        .WithMany()
                        .HasForeignKey("SchoolEventId");

                    b.HasOne("CSMWebsite2023.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("SchoolEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.SchoolEventShare", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.SchoolEvent", "SchoolEvent")
                        .WithMany()
                        .HasForeignKey("SchoolEventId");

                    b.HasOne("CSMWebsite2023.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("SchoolEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.SchoolPost", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.SchoolPostComment", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.SchoolPost", "SchoolPost")
                        .WithMany()
                        .HasForeignKey("SchoolPostId");

                    b.HasOne("CSMWebsite2023.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("SchoolPost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.SchoolPostMedium", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.SchoolPost", "SchoolPost")
                        .WithMany()
                        .HasForeignKey("SchoolPostId");

                    b.Navigation("SchoolPost");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.SchoolPostReaction", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.SchoolPost", "SchoolPost")
                        .WithMany()
                        .HasForeignKey("SchoolPostId");

                    b.HasOne("CSMWebsite2023.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("SchoolPost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMWebsite2023.Data.Models.SchoolPostShare", b =>
                {
                    b.HasOne("CSMWebsite2023.Data.Models.SchoolPost", "SchoolPost")
                        .WithMany()
                        .HasForeignKey("SchoolPostId");

                    b.HasOne("CSMWebsite2023.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("SchoolPost");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
